import { Link } from "react-router-dom";
import "./HomePage.css";

function HomePage() {
  return (
    <div className="home-page">
      <nav className="home-nav">
        <div className="logo">SciMentor AI ✨</div>
        <div className="nav-actions">
          <Link to="/login" className="nav-link">Login</Link>
          <Link to="/register" className="btn btn-primary">Get Started</Link>
        </div>
      </nav>

      <section className="hero">
        <div className="hero-content">
          <span className="badge">AI-Powered Learning Platform</span>

          <h1>Learn science with your personal AI mentor.</h1>

          <p>
            Choose a field, select a focused topic, ask what you want to learn,
            and get a clear, structured mini-lesson generated by AI.
          </p>

          <div className="hero-buttons">
            <Link to="/register" className="btn btn-primary">Start Learning</Link>
            <Link to="/login" className="btn btn-light">I already have an account</Link>
          </div>
        </div>

        <div className="hero-card card">
          <h3>Today’s learning flow 📚</h3>
          <ul>
            <li>Choose a science category</li>
            <li>Select a sub-topic</li>
            <li>Ask your learning question</li>
            <li>Receive a focused AI lesson</li>
          </ul>
        </div>
      </section>

      <section className="features">
        <div className="feature-card card">
          <h3>🎯 Focused Topics</h3>
          <p>Learn by category and sub-category, not by random chat.</p>
        </div>

        <div className="feature-card card">
          <h3>🤖 AI Lessons</h3>
          <p>Receive short, structured explanations that are pleasant to read.</p>
        </div>

        <div className="feature-card card">
          <h3>🕘 Saved History</h3>
          <p>Return to your previous lessons whenever you want.</p>
        </div>
      </section>
    </div>
  );
}

export default HomePage;